<center><h2> Machine Learning</h2></center>

<center><img src="./anonymous.jpg" width="400" height="100"></center>

In [4]:
import numpy as np

In [7]:
x = np.array([1,2,3,4])

In [8]:
x

array([1, 2, 3, 4])

In [9]:
print(x.size)
len(x)

4


4

In [10]:
x.itemsize

4

In [11]:
x.dtype

dtype('int32')

In [18]:
x = x.astype('int64')

In [19]:
x.itemsize

8

In [20]:
import sys

In [21]:
sys.getsizeof(x)

128

In [22]:
x

array([1, 2, 3, 4], dtype=int64)

In [23]:
x.dtype

dtype('int64')

In [24]:
a = 5

In [25]:
a

5

In [27]:
type(a)

int

In [29]:
sys.getsizeof(a)

28

In [30]:
del a

In [31]:
type(x)

numpy.ndarray

In [32]:
r = range(1,10)

In [33]:
type(r)

range

In [34]:
a = np.arange(21 , 10 ,-2)

In [35]:
a

array([21, 19, 17, 15, 13, 11])

In [36]:
type(a)

numpy.ndarray

In [69]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
# a1 = np.array([[[1,2,3,4,5],[4,5,6,4,5],[7,8,9,4,5]]])
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [70]:
type(l1)
# type(a1)

list

In [71]:
a1.ndim

2

In [72]:
# l1.ndim

In [73]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
l1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [59]:
y = np.array([1,2,3])

In [60]:
y

array([1, 2, 3])

In [62]:
y = np.asarray(y)
y

array([1, 2, 3])

In [75]:
del y

In [77]:
l1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# 

In [78]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
l1[1][1]

5

In [81]:
a1[2][-1]

9

In [82]:
# a1[row,col]

In [83]:
a1[:,-1]

array([3, 6, 9])

In [84]:
a1[0:1,-1]

array([3])

In [85]:
a1[0:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [86]:
print(np.mean(a1))
print(np.sum(a1))
print(np.std(a1))
print(np.min(a1))
print(np.max(a1))


5.0
45
2.581988897471611
1
9


In [87]:
a1**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [88]:
a1>4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [89]:
b = a1>4

In [90]:
b

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [91]:
a1[b]

array([5, 6, 7, 8, 9])