In [1]:
import numpy as np

In [2]:
x = np.arange(25).reshape(5,5)

In [3]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
x1 = np.eye(3)

In [5]:
x1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
x2 = np.linspace(3,8,10)

In [7]:
x2

array([3.        , 3.55555556, 4.11111111, 4.66666667, 5.22222222,
       5.77777778, 6.33333333, 6.88888889, 7.44444444, 8.        ])

In [40]:
x3 = np.ones((4,3,5))
x3

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [43]:
x4 = np.zeros((4,1,3))
x4

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [50]:
x5 = np.empty((3,3))
x5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [54]:
print(np.vstack((v1,v2)))
print(np.hstack((v1,v2)))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [55]:
v1

array([1, 2, 3, 4])

In [56]:
type(v1)

numpy.ndarray

In [57]:
v1.ndim

1

In [58]:
v1.shape

(4,)

In [59]:
type(x)

numpy.ndarray

In [60]:
x.shape

(5, 5)

In [61]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
x.ndim

2

In [63]:
x.shape

(2, 3)

In [64]:
x.size

6

In [67]:
x.dtype.itemsize

4

In [68]:
x.data